teams = {
            'twins': {
                '4': ['white sox', 'guardians', 'tigers', 'royals', 'white sox', 'guardians', 'tigers',
                      'royals', "brewers"],
                '3': ['white sox', 'guardians', 'tigers', 'royals', 'mariners', 'astros', 'rangers', 'angels',
                      'athletics', 'baltimore', 'red sox', 'yankees', 'rays', 'blue jays', 'cubs',
                      'cardinals', 'reds', 'pirates', 'dodgers', 'giants', 'rockies', 'diamondbacks', 'padres',
                      'mets', 'nationals', 'phillies', 'marlins', 'braves', 'white sox', 'guardians', 'tigers',
                      'royals', 'mariners', 'astros', 'rangers', 'angels', 'athletics', 'baltimore', 'red sox',
                      'yankees', 'rays', 'blue jays']},

            'white sox': {
                '4': ['twins', 'guardians', 'tigers', 'royals', 'twins', 'guardians', 'tigers', 'royals', "cubs"],
                '3': ['twins', 'guardians', 'tigers', 'royals', 'mariners', 'astros', 'rangers', 'angels',
                      'athletics', 'baltimore', 'red sox', 'yankees', 'rays', 'blue jays', 'brewers',
                      'cardinals', 'reds', 'pirates', 'dodgers', 'giants', 'rockies', 'diamondbacks', 'padres',
                      'mets', 'nationals', 'phillies', 'marlins', 'braves', 'twins', 'guardians', 'tigers',
                      'royals', 'mariners', 'astros', 'rangers', 'angels', 'athletics', 'baltimore', 'red sox',
                      'yankees', 'rays', 'blue jays']},

            'guardians': {
                '4': ['twins', 'white sox', 'tigers', 'royals', 'twins', 'white sox', 'tigers', 'royals', "reds"],
                '3': ['twins', 'white sox', 'tigers', 'royals', 'mariners', 'astros', 'rangers', 'angels',
                      'athletics', 'baltimore', 'red sox', 'yankees', 'rays', 'blue jays', 'cubs', 'brewers',
                      'cardinals', 'pirates', 'dodgers', 'giants', 'rockies', 'diamondbacks', 'padres',
                      'mets', 'nationals', 'phillies', 'marlins', 'braves', 'twins', 'white sox', 'tigers',
                      'royals', 'mariners', 'astros', 'rangers', 'angels', 'athletics', 'baltimore', 'red sox',
                      'yankees', 'rays', 'blue jays']},

            'tigers': {
                '4': ['twins', 'white sox', 'guardians', 'royals', 'twins', 'white sox', 'guardians', 'royals', "pirates"],
                '3': ['twins', 'white sox', 'guardians', 'royals', 'mariners', 'astros', 'rangers',
                      'angels', 'athletics', 'baltimore', 'red sox', 'yankees', 'rays', 'blue jays',
                      'cubs', 'brewers', 'cardinals', 'reds', 'dodgers', 'giants', 'rockies',
                      'diamondbacks', 'padres', 'mets', 'nationals', 'phillies', 'marlins', 'braves',
                      'twins', 'white sox', 'guardians', 'royals', 'mariners', 'astros', 'rangers',
                      'angels', 'athletics', 'baltimore', 'red sox', 'yankees', 'rays', 'blue jays']},
            'royals': {
                '4': ['twins', 'white sox', 'guardians', 'tigers', 'twins', 'white sox', 'guardians', 'tigers', "cardinals"],
                '3': ['twins', 'white sox', 'guardians', 'tigers', 'mariners', 'astros', 'rangers', 'angels',
                      'athletics', 'baltimore', 'red sox', 'yankees', 'rays', 'blue jays', 'cubs', 'brewers',
                      'reds', 'pirates', 'dodgers', 'giants', 'rockies', 'diamondbacks', 'padres',
                      'mets', 'nationals', 'phillies', 'marlins', 'braves', 'twins', 'white sox', 'guardians',
                      'tigers', 'mariners', 'astros', 'rangers', 'angels', 'athletics', 'baltimore', 'red sox',
                      'yankees', 'rays', 'blue jays']},
            'mariners': {
                '4': ['astros', 'rangers', 'angels', 'athletics', 'astros', 'rangers', 'angels', 'athletics', "padres"],
                '3': ['twins', 'white sox', 'guardians', 'tigers', 'royals', 'astros', 'rangers', 'angels',
                      'athletics', 'baltimore', 'red sox', 'yankees', 'rays', 'blue jays', 'cubs', 'brewers',
                      'cardinals', 'reds', 'pirates', 'dodgers', 'giants', 'rockies', 'diamondbacks',
                      'mets', 'nationals', 'phillies', 'marlins', 'braves', 'twins', 'white sox', 'guardians',
                      'tigers', 'royals', 'astros', 'rangers', 'angels', 'athletics', 'baltimore', 'red sox',
                      'yankees', 'rays', 'blue jays']},
            'astros': {
                '4': ['mariners', 'rangers', 'angels', 'athletics', 'mariners', 'rangers', 'angels',
                      'athletics', "diamondbacks"],
                '3': ['twins', 'white sox', 'guardians', 'tigers', 'royals', 'mariners', 'rangers', 'angels',
                      'athletics', 'baltimore', 'red sox', 'yankees', 'rays', 'blue jays', 'cubs', 'brewers',
                      'cardinals', 'reds', 'pirates', 'dodgers', 'giants', 'rockies', 'padres', 'mets',
                      'nationals', 'phillies', 'marlins', 'braves', 'twins', 'white sox', 'guardians', 'tigers',
                      'royals', 'mariners', 'rangers', 'angels', 'athletics', 'baltimore', 'red sox', 'yankees',
                      'rays', 'blue jays']},
            'rangers': {
                '4': ['mariners', 'astros', 'angels', 'athletics', 'mariners', 'astros', 'angels', 'athletics', "rockies"],
                '3': ['twins', 'white sox', 'guardians', 'tigers', 'royals', 'mariners', 'astros', 'angels',
                      'athletics', 'baltimore', 'red sox', 'yankees', 'rays', 'blue jays', 'cubs', 'brewers',
                      'cardinals', 'reds', 'pirates', 'dodgers', 'giants', 'diamondbacks', 'padres',
                      'mets', 'nationals', 'phillies', 'marlins', 'braves', 'twins', 'white sox', 'guardians',
                      'tigers', 'royals', 'mariners', 'astros', 'angels', 'athletics', 'baltimore', 'red sox',
                      'yankees', 'rays', 'blue jays']},
            'angels': {
                '4': ['mariners', 'astros', 'rangers', 'athletics', 'mariners', 'astros', 'rangers',
                      'athletics', "dodgers"],
                '3': ['twins', 'white sox', 'guardians', 'tigers', 'royals', 'mariners', 'astros', 'rangers',
                      'athletics', 'baltimore', 'red sox', 'yankees', 'rays', 'blue jays', 'cubs', 'brewers',
                      'cardinals', 'reds', 'pirates', 'giants', 'rockies', 'diamondbacks', 'padres',
                      'mets', 'nationals', 'phillies', 'marlins', 'braves', 'twins', 'white sox', 'guardians',
                      'tigers', 'royals', 'mariners', 'astros', 'rangers', 'athletics', 'baltimore', 'red sox',
                      'yankees', 'rays', 'blue jays']},
            'athletics': {
                '4': ['mariners', 'astros', 'rangers', 'angels', 'mariners', 'astros', 'rangers', 'angels', "giants"],
                '3': ['twins', 'white sox', 'guardians', 'tigers', 'royals', 'mariners', 'astros', 'rangers',
                      'angels', 'baltimore', 'red sox', 'yankees', 'rays', 'blue jays', 'cubs', 'brewers',
                      'cardinals', 'reds', 'pirates', 'dodgers', 'rockies', 'diamondbacks',
                      'padres', 'mets', 'nationals', 'phillies', 'marlins', 'braves', 'twins', 'white sox',
                      'guardians', 'tigers', 'royals', 'mariners', 'astros', 'rangers', 'angels', 'baltimore',
                      'red sox', 'yankees', 'rays', 'blue jays']},
            'baltimore': {
                '4': ['red sox', 'yankees', 'rays', 'blue jays', 'red sox', 'yankees', 'rays', 'blue jays', "nationals"],
                '3': ['twins', 'white sox', 'guardians', 'tigers', 'royals', 'mariners', 'astros', 'rangers',
                      'angels', 'athletics', 'red sox', 'yankees', 'rays', 'blue jays', 'cubs', 'brewers',
                      'cardinals', 'reds', 'pirates', 'dodgers', 'giants', 'rockies', 'diamondbacks',
                      'padres', 'mets', 'phillies', 'marlins', 'braves', 'twins', 'white sox',
                      'guardians', 'tigers', 'royals', 'mariners', 'astros', 'rangers', 'angels', 'athletics',
                      'red sox', 'yankees', 'rays', 'blue jays']},
            'red sox': {
                '4': ['baltimore', 'yankees', 'rays', 'blue jays', 'baltimore', 'yankees', 'rays', 'blue jays', "braves"],
                '3': ['twins', 'white sox', 'guardians', 'tigers', 'royals', 'mariners', 'astros', 'rangers',
                      'angels', 'athletics', 'baltimore', 'yankees', 'rays', 'blue jays', 'cubs', 'brewers',
                      'cardinals', 'reds', 'pirates', 'dodgers', 'giants', 'rockies', 'diamondbacks', 'padres',
                      'mets', 'nationals', 'phillies', 'marlins', 'twins', 'white sox', 'guardians',
                      'tigers', 'royals', 'mariners', 'astros', 'rangers', 'angels', 'athletics', 'baltimore',
                      'yankees', 'rays', 'blue jays']},
            'yankees': {
                '4': ['baltimore', 'red sox', 'rays', 'blue jays', 'baltimore', 'red sox', 'rays', 'blue jays', "mets"],
                '3': ['twins', 'white sox', 'guardians', 'tigers', 'royals', 'mariners', 'astros', 'rangers',
                      'angels', 'athletics', 'baltimore', 'red sox', 'rays', 'blue jays', 'cubs', 'brewers',
                      'cardinals', 'reds', 'pirates', 'dodgers', 'giants', 'rockies', 'diamondbacks', 'padres',
                      'nationals', 'phillies', 'marlins', 'braves', 'twins', 'white sox', 'guardians',
                      'tigers', 'royals', 'mariners', 'astros', 'rangers', 'angels', 'athletics', 'baltimore',
                      'red sox', 'rays', 'blue jays']},
            'rays': {
                '4': ['baltimore', 'red sox', 'yankees', 'blue jays', 'baltimore', 'red sox', 'yankees',
                      'blue jays', "marlins"],
                '3': ['twins', 'white sox', 'guardians', 'tigers', 'royals', 'mariners', 'astros', 'rangers', 'angels',
                      'athletics', 'baltimore', 'red sox', 'yankees', 'blue jays', 'cubs', 'brewers', 'cardinals',
                      'reds', 'pirates', 'dodgers', 'giants', 'rockies', 'diamondbacks', 'padres', 'mets', 'nationals',
                      'phillies', 'braves', 'twins', 'white sox', 'guardians', 'tigers', 'royals',
                      'mariners', 'astros', 'rangers', 'angels', 'athletics', 'baltimore', 'red sox', 'yankees',
                      'blue jays']},
            'blue jays': {
                '4': ['baltimore', 'red sox', 'yankees', 'rays', 'baltimore', 'red sox', 'yankees', 'rays', "phillies"],
                '3': ['twins', 'white sox', 'guardians', 'tigers', 'royals', 'mariners', 'astros', 'rangers',
                      'angels', 'athletics', 'baltimore', 'red sox', 'yankees', 'rays', 'cubs', 'brewers',
                      'cardinals', 'reds', 'pirates', 'dodgers', 'giants', 'rockies', 'diamondbacks',
                      'padres', 'mets', 'nationals', 'marlins', 'braves', 'twins', 'white sox',
                      'guardians', 'tigers', 'royals', 'mariners', 'astros', 'rangers', 'angels', 'athletics',
                      'baltimore', 'red sox', 'yankees', 'rays']},
            'cubs': {
                '4': ['brewers', 'cardinals', 'reds', 'pirates', 'brewers', 'cardinals', 'reds', 'pirates', "white sox"],
                '3': ['twins', 'guardians', 'tigers', 'royals', 'mariners', 'astros', 'rangers', 'angels',
                      'athletics', 'baltimore', 'red sox', 'yankees', 'rays', 'blue jays', 'brewers', 'cardinals',
                      'reds', 'pirates', 'dodgers', 'giants', 'rockies', 'diamondbacks', 'padres', 'mets', 'nationals',
                      'phillies', 'marlins', 'braves', 'brewers', 'cardinals', 'reds', 'pirates', 'dodgers',
                      'giants', 'rockies', 'diamondbacks', 'padres', 'mets', 'nationals', 'phillies', 'marlins',
                      'braves']},
            'brewers': {'4': ['cubs', 'cardinals', 'reds', 'pirates', 'cubs', 'cardinals', 'reds', 'pirates', "twins"],
                        '3': ['white sox', 'guardians', 'tigers', 'royals', 'mariners', 'astros', 'rangers',
                              'angels', 'athletics', 'baltimore', 'red sox', 'yankees', 'rays', 'blue jays', 'cubs',
                              'cardinals', 'reds', 'pirates', 'dodgers', 'giants', 'rockies', 'diamondbacks', 'padres',
                              'mets', 'nationals', 'phillies', 'marlins', 'braves', 'cubs', 'cardinals', 'reds', 'pirates',
                              'dodgers', 'giants', 'rockies', 'diamondbacks', 'padres', 'mets', 'nationals', 'phillies',
                              'marlins', 'braves']},
            'cardinals': {'4': ['cubs', 'brewers', 'reds', 'pirates', 'cubs', 'brewers', 'reds', 'pirates', "royals"],
                          '3': ['twins', 'white sox', 'guardians', 'tigers', 'mariners', 'astros', 'rangers',
                                'angels', 'athletics', 'baltimore', 'red sox', 'yankees', 'rays', 'blue jays', 'cubs',
                                'brewers', 'reds', 'pirates', 'dodgers', 'giants', 'rockies', 'diamondbacks', 'padres',
                                'mets', 'nationals', 'phillies', 'marlins', 'braves', 'cubs', 'brewers', 'reds', 'pirates',
                                'dodgers', 'giants', 'rockies', 'diamondbacks', 'padres', 'mets', 'nationals',
                                'phillies', 'marlins', 'braves']},
            'reds': {
                '4': ['cubs', 'brewers', 'cardinals', 'pirates', 'cubs', 'brewers', 'cardinals', 'pirates', "guardians"],
                '3': ['twins', 'white sox', 'tigers', 'royals', 'mariners', 'astros', 'rangers', 'angels',
                      'athletics', 'baltimore', 'red sox', 'yankees', 'rays', 'blue jays', 'cubs', 'brewers',
                      'cardinals', 'pirates', 'dodgers', 'giants', 'rockies', 'diamondbacks', 'padres', 'mets',
                      'nationals', 'phillies', 'marlins', 'braves', 'cubs', 'brewers', 'cardinals', 'pirates',
                      'dodgers', 'giants', 'rockies', 'diamondbacks', 'padres', 'mets', 'nationals',
                      'phillies', 'marlins', 'braves']},
            'pirates': {'4': ['cubs', 'brewers', 'cardinals', 'reds', 'cubs', 'brewers', 'cardinals', 'reds', "tigers"],
                        '3': ['twins', 'white sox', 'guardians', 'royals', 'mariners', 'astros', 'rangers',
                              'angels', 'athletics', 'baltimore', 'red sox', 'yankees', 'rays', 'blue jays', 'cubs',
                              'brewers', 'cardinals', 'reds', 'dodgers', 'giants', 'rockies', 'diamondbacks', 'padres',
                              'mets', 'nationals', 'phillies', 'marlins', 'braves', 'cubs', 'brewers', 'cardinals', 'reds',
                              'dodgers', 'giants', 'rockies', 'diamondbacks', 'padres', 'mets', 'nationals', 'phillies',
                              'marlins', 'braves']},
            'dodgers': {
                '4': ['giants', 'rockies', 'diamondbacks', 'padres', 'giants', 'rockies', 'diamondbacks',
                      'padres', "angels"],
                '3': ['twins', 'white sox', 'guardians', 'tigers', 'royals', 'mariners', 'astros', 'rangers',
                      'athletics', 'baltimore', 'red sox', 'yankees', 'rays', 'blue jays', 'cubs',
                      'brewers', 'cardinals', 'reds', 'pirates', 'giants', 'rockies', 'diamondbacks', 'padres',
                      'mets', 'nationals', 'phillies', 'marlins', 'braves', 'cubs', 'brewers', 'cardinals',
                      'reds', 'pirates', 'giants', 'rockies', 'diamondbacks', 'padres', 'mets', 'nationals', 'phillies',
                      'marlins', 'braves']},
            'giants': {
                '4': ['dodgers', 'rockies', 'diamondbacks', 'padres', 'dodgers', 'rockies', 'diamondbacks',
                      'padres', "athletics"],
                '3': ['twins', 'white sox', 'guardians', 'tigers', 'royals', 'mariners', 'astros', 'rangers',
                      'angels', 'baltimore', 'red sox', 'yankees', 'rays', 'blue jays', 'cubs', 'brewers',
                      'cardinals', 'reds', 'pirates', 'dodgers', 'rockies', 'diamondbacks', 'padres', 'mets', 'nationals',
                      'phillies', 'marlins', 'braves', 'cubs', 'brewers', 'cardinals', 'reds', 'pirates', 'dodgers',
                      'rockies', 'diamondbacks', 'padres', 'mets', 'nationals', 'phillies', 'marlins', 'braves']},
            'rockies': {
                '4': ['dodgers', 'giants', 'diamondbacks', 'padres', 'dodgers', 'giants', 'diamondbacks',
                      'padres', "rangers"],
                '3': ['twins', 'white sox', 'guardians', 'tigers', 'royals', 'mariners', 'astros',
                      'angels', 'athletics', 'baltimore', 'red sox', 'yankees', 'rays', 'blue jays', 'cubs',
                      'brewers', 'cardinals', 'reds', 'pirates', 'dodgers', 'giants', 'diamondbacks', 'padres',
                      'mets', 'nationals', 'phillies', 'marlins', 'braves', 'cubs', 'brewers', 'cardinals',
                      'reds', 'pirates', 'dodgers', 'giants', 'diamondbacks', 'padres', 'mets', 'nationals', 'phillies',
                      'marlins', 'braves']},
            'diamondbacks': {
                '4': ['dodgers', 'giants', 'rockies', 'padres', 'dodgers', 'giants', 'rockies', 'padres', "astros"],
                '3': ['twins', 'white sox', 'guardians', 'tigers', 'royals', 'mariners',
                      'rangers', 'angels', 'athletics', 'baltimore', 'red sox', 'yankees', 'rays', 'blue jays',
                      'cubs', 'brewers', 'cardinals', 'reds', 'pirates', 'dodgers', 'giants', 'rockies', 'padres',
                      'mets', 'nationals', 'phillies', 'marlins', 'braves', 'cubs', 'brewers', 'cardinals',
                      'reds', 'pirates', 'dodgers', 'giants', 'rockies', 'padres', 'mets', 'nationals',
                      'phillies', 'marlins', 'braves']},
            'padres': {
                '4': ['dodgers', 'giants', 'rockies', 'diamondbacks', 'dodgers', 'giants', 'rockies',
                      'diamondbacks', "mariners"],
                '3': ['twins', 'white sox', 'guardians', 'tigers', 'royals', 'astros', 'rangers',
                      'angels', 'athletics', 'baltimore', 'red sox', 'yankees', 'rays', 'blue jays', 'cubs', 'brewers',
                      'cardinals', 'reds', 'pirates', 'dodgers', 'giants', 'rockies', 'diamondbacks', 'mets', 'nationals',
                      'phillies', 'marlins', 'braves', 'cubs', 'brewers', 'cardinals', 'reds', 'pirates', 'dodgers',
                      'giants', 'rockies', 'diamondbacks', 'mets', 'nationals', 'phillies', 'marlins', 'braves']},
        'mets': {
            '4': ['nationals', 'phillies', 'marlins', 'braves', 'nationals', 'phillies', 'marlins', 'braves', "yankees"],
            '3': ['twins', 'white sox', 'guardians', 'tigers', 'royals', 'mariners', 'astros', 'rangers',
                  'angels', 'athletics', 'baltimore', 'red sox', 'rays', 'blue jays', 'cubs', 'brewers',
                  'cardinals', 'reds', 'pirates', 'dodgers', 'giants', 'rockies', 'diamondbacks', 'padres',
                  'nationals', 'phillies', 'marlins', 'braves', 'cubs', 'brewers', 'cardinals', 'reds',
                  'pirates', 'dodgers', 'giants', 'rockies', 'diamondbacks', 'padres', 'nationals', 'phillies', 'marlins', 'braves']},

        'nationals': {'4': ['mets', 'phillies', 'marlins', 'braves', 'mets', 'phillies', 'marlins', 'braves', "baltimore"],
                      '3': ['twins', 'white sox', 'guardians', 'tigers', 'royals', 'mariners', 'astros',
                            'rangers', 'angels', 'athletics', 'red sox', 'yankees', 'rays',
                            'blue jays', 'cubs', 'brewers', 'cardinals', 'reds', 'pirates', 'dodgers', 'giants',
                            'rockies', 'diamondbacks', 'padres', 'mets', 'phillies', 'marlins', 'braves', 'cubs',
                            'brewers', 'cardinals', 'reds', 'pirates', 'dodgers', 'giants', 'rockies', 'diamondbacks',
                            'padres', 'mets', 'phillies', 'marlins', 'braves']},

        'phillies': {'4': ['mets', 'nationals', 'marlins', 'braves', 'mets', 'nationals', 'marlins', 'braves', "blue jays"],
                     '3': ['twins', 'white sox', 'guardians', 'tigers', 'royals', 'mariners', 'astros',
                           'rangers', 'angels', 'athletics', 'baltimore', 'red sox', 'yankees', 'rays',
                           'cubs', 'brewers', 'cardinals', 'reds', 'pirates', 'dodgers', 'giants', 'rockies',
                           'diamondbacks', 'padres', 'mets', 'nationals', 'marlins', 'braves', 'cubs', 'brewers', 'cardinals',
                           'reds', 'pirates', 'dodgers', 'giants', 'rockies', 'diamondbacks', 'padres', 'mets',
                           'nationals', 'marlins', 'braves']},

        'marlins': {'4': ['mets', 'nationals', 'phillies', 'braves', 'mets', 'nationals', 'phillies', 'braves', "rays"],
                    '3': ['twins', 'white sox', 'guardians', 'tigers', 'royals', 'mariners', 'astros',
                          'rangers', 'angels', 'athletics', 'baltimore', 'red sox', 'yankees', 'blue jays', 'cubs',
                          'brewers', 'cardinals', 'reds', 'pirates', 'dodgers', 'giants', 'rockies',
                          'diamondbacks', 'padres', 'mets', 'nationals', 'phillies', 'braves', 'cubs', 'brewers', 'cardinals',
                          'reds', 'pirates', 'dodgers', 'giants', 'rockies', 'diamondbacks', 'padres', 'mets',
                          'nationals', 'phillies', 'braves']},

        'braves': {
            '4': ['mets', 'nationals', 'phillies', 'marlins', 'mets', 'nationals', 'phillies', 'marlins', "red sox"],
            '3': ['twins', 'white sox', 'guardians', 'tigers', 'royals', 'mariners', 'astros', 'rangers',
                  'angels', 'athletics', 'baltimore', 'yankees', 'rays', 'blue jays', 'cubs',
                  'brewers', 'cardinals', 'reds', 'pirates', 'dodgers', 'giants', 'rockies', 'diamondbacks',
                  'padres', 'mets', 'nationals', 'phillies', 'marlins', 'cubs', 'brewers', 'cardinals',
                  'reds', 'pirates', 'dodgers', 'giants', 'rockies', 'diamondbacks', 'padres', 'mets', 'nationals',
                  'phillies', 'marlins']}}
